#!/bin/sh
# Regenerates ios/Lime.xcodeproj from project.yml (the .xcodeproj is gitignored).
set -e
cd "$(dirname "$0")"
command -v xcodegen >/dev/null 2>&1 || { echo "XcodeGen is missing: brew install xcodegen" >&2; exit 1; }

# The backend the app talks to: the Supabase project URL and its PUBLIC anon key (both are meant to
# ship inside an app). They come from supabase/.staging.public.env, which deploy-staging.sh writes
# (gitignored); with no such file the app is built without a backend and says so. The service-role
# key is never read here.
BACKEND_FILE="Lime/Config/BackendConfig.generated.swift"
PUBLIC_ENV="../supabase/.staging.public.env"
URL=""
KEY=""
if [ -f "$PUBLIC_ENV" ]; then
  URL="$(sed -n 's/^SUPABASE_URL=//p' "$PUBLIC_ENV" | head -1)"
  KEY="$(sed -n 's/^SUPABASE_ANON_KEY=//p' "$PUBLIC_ENV" | head -1)"
fi
{
  echo "// Generated by ios/generate.sh from supabase/.staging.public.env. Do not edit or commit."
  if [ -n "$URL" ] && [ -n "$KEY" ]; then
    echo "enum GeneratedBackend {"
    echo "    static let url: String? = \"$URL\""
    echo "    static let apiKey: String? = \"$KEY\""
    echo "}"
  else
    echo "enum GeneratedBackend {"
    echo "    static let url: String? = nil"
    echo "    static let apiKey: String? = nil"
    echo "}"
  fi
} > "$BACKEND_FILE"

# LimeCore (Rust): builds the static libs, the Swift bindings and the xcframework the project links.
../core/build-ios.sh
xcodegen generate --spec project.yml
